-- Generated by IntelliJ

drop table if exists AUTHOR;
drop table if exists BOOK;
drop table if exists BOOK_AUTHOR;


create table AUTHOR
(
	ID IDENTITY primary key,
	NAME VARCHAR(255) not null
)
;

create table BOOK
(
	ID IDENTITY primary key,
	TITLE VARCHAR(500) not null,
	ISBN VARCHAR(20),
	YEAR VARCHAR(4),
	FORMAT VARCHAR(12) not null,
	PAGES SMALLINT
)
;

create table BOOK_AUTHOR
(
	BOOK_ID LONG not null,
	AUTHOR_ID LONG not null,
	constraint BOOK_AUTHOR_AUTHOR_ID_FK
		foreign key (AUTHOR_ID) references AUTHOR,
	constraint BOOK_AUTHOR_BOOK_ID_FK
		foreign key (BOOK_ID) references BOOK
)
;

